<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NmsTracker.Application\NmsTracker.Application.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="libNOM.io"/>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Saves\" />
    </ItemGroup>

</Project>
