<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\NmsTracker.Domain\NmsTracker.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="System.Reactive"/>
        <PackageReference Include="System.Reactive.Linq"/>
    </ItemGroup>
</Project>
