name: CI
on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:
    
env:
  Solution_Name: NmsTracker.sln
  Test_Dir: tests
  Build_Config_Debug: Debug
  Build_Config_Release: Release

jobs:
  build:      
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json
            tests/**/packages.lock.json

      - name: Restore
        run: dotnet restore ${{ env.Solution_Name }} --locked-mode
        
      - name: Build
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            dotnet build ${{ env.Solution_Name }} -c ${{ env.Build_Config_Debug }} --no-restore --interactive=false \ 
          --nologo 
          else
            dotnet build ${{ env.Solution_Name }} -c ${{ env.Build_Config_Release }} --no-restore
          fi
      - name: Publish Build
        id: publish
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: |
            src/**/bin
            src/**/obj
            tests/**/bin
            tests/**/obj

  roslyn:
    name: Roslyn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
          cache: true
          cache-dependency-path: |
            src/**/packages.lock.json
            tests/**/packages.lock.json
      - name: Lint (dotnet format)
        run: | 
          dotnet format \
          --no-restore \
          --verify-no-changes \
          --verbosity normal \
          --severity warn \
          --report roslyn-results.sarif.json

      - name: Upload Roslyn SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: roslyn-results.sarif.json
    
  resharper:
    name: ReSharper
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: ReSharper InspectCode
        uses: JetBrains/ReSharper-InspectCode@v0.11
        with:
          properties: 'RunAnalyzers=false'
          build: 'False'
          swea: true
          verbosity: 'WARN'
          sEverity: 'WARN'
          settings: .editorconfig
          solution: ${{ env.Solution_Name }}
          output: resharper-results.sarif.json
          
      - name: Upload ReSharper SARIF
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: resharper-results.sarif.json
          
  tests:
    name: Unit Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download Build Artifacts
        uses: actions/download-artifact@v5
        with:
          name: build-artifact
            
      - name: Unit Tests
        run: dotnet test --no-build --logger "trx;LogFileName=TestResults.trx"
        
      - name: Publish Test Results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./src/Test/TestResults/TestResults.trx